site_name: NFDI Best Practices
theme:
  name: material
  logo: images/logo/logo.svg
  favicon: images/logo/logo.svg
  palette:
    # default to light theme
    - scheme: default
      primary: custom # oep primary color
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css