name: Deploy MkDocs Site to GitHub Pages

on:
  push:
    branches:
      - develop  # Trigger this action when there is a push to the develop branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install MkDocs and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Build MkDocs site
      run: mkdocs build

    - name: Deploy to GitHub Pages
      run: mkdocs gh-deploy --force
      env:
        CI: false
